[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]
description = "A new attempt at writing a simple raytracer. This time, no fumbling about with real-time stuff, but instead creating a good-old, offline renderer. Based on <https://raytracing.github.io/books/RayTracingInOneWeekend.html>."


[dependencies]
clap     = "4.2"
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
log      = "0.4"
